name: Check

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Check typescript
        run: npm run ts:check
      - name: Run Lint
        run: npm run lint
